### ISSUE TITLE
Consider adding functional tests to this project

### ISSUE THREAD

**Issue by danielbachhuber** [ernilambar/database-command#1]
Functional tests are an integral ingredient of highly-quality, maintainable commands. WP-CLI tries to make it as easy as possible to add functional tests to your package with its `wp scaffold package-tests` command:

https://github.com/wp-cli/scaffold-package-command#wp-scaffold-package-tests

I'd encourage you to consider adding functional tests to your package :) By starting your functional tests early on, it also makes it much easier to maintain your project over time.

**Comment by ernilambar** [comment]
I will surely look into that. Personally I wish this command will be eventually merge into core `db`. :)

**Comment by ernilambar** [comment]
@danielbachhuber I have added some functional tests. Can you please check it and provide suggestions to improve it? I adore you and I am learning a lot from you. Thanks :)

**Comment by danielbachhuber** [comment]
> Can you please check it and provide suggestions to improve it?

It looks like a pretty good start! I like how you're testing the expected errors.

Based on what I've seen, I personally would add more tests around the database reset behavior. More specifically, when the command is run successfully, add tests for all of the values that have been expected to be changed.

Because the command resets tables, you could use `wp (post|user|term|comment) generate` to generate dummy data, and then make sure the data has been deleted.

> I adore you and I am learning a lot from you. Thanks :)

Aw, thanks :) Hope these are helpful suggestions.

**Comment by ernilambar** [comment]
Tests are updated.
