### ISSUE TITLE
Clarify project description

### ISSUE THREAD

**Issue by danielbachhuber** [ernilambar/database-command#2]
The project description is currently:

> Database tool to reset WordPress

WP-CLI already includes `wp db reset`. It would be helpful to expand your description and explain how this is different from existing commands.

**Comment by ernilambar** [comment]
Ok sure. I will update it and add more explanation. I have one question. How do I version package? Tagging? Will older version of user update to latest if tag newer version, Like in WordPress plugins :)

**Comment by danielbachhuber** [comment]
> How do I version package? Tagging?

Yes, you should follow [semver](http://semver.org/). Your first version would be `v0.1.0` and you'd create a Git tag accordingly. Github's releases feature is nice for this.

>  Will older version of user update to latest if tag newer version, Like in WordPress plugins :)

Not quite yet: https://github.com/wp-cli/wp-cli/issues/2544

For now, a user can update by running `wp package install ernilambar/database-command` a second time.

**Comment by ernilambar** [comment]
Fixed in https://github.com/ernilambar/database-command/commit/31d8cbe3e5b9c6e0fcd0e234b34b5b28e7ac68e8
